import Link from "next/link";
import { ArrowRight } from "lucide-react";
import BlogCard from "@/components/blog-card";

const posts = [
  {
    id: "post-1",
    title: "Getting Started with Next.js",
    slug: "getting-started-with-nextjs",
    excerpt:
      "Learn how to build modern web applications with Next.js, the React framework for production.",
    content: `
# Getting Started with Next.js

Next.js is a React framework that enables several extra features, including server-side rendering and generating static websites.

Next.js provides a solution to all of these problems. But more importantly, it puts you and your team in the pit of success when building React applications.

## Why Next.js?

Here's why you should consider Next.js for your next web project:

- Server-side rendering
- Static site generation
- TypeScript support
- Route pre-fetching
- Built-in CSS and Sass support
- Fast refresh
- File-system routing
- API routes

## Code Example

\`\`\`javascript
// pages/index.js
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Next.js!</h1>
      </main>
    </div>
  )
}
\`\`\`
    `,
    coverImage: "/placeholder.svg?height=630&width=1200",
    publishedAt: "2023-05-15T10:00:00Z",
    authorId: "author-1",
    author: {
      id: "author-2",
      name: "Jane Smith",
      email: "jane@example.com",
      avatar: "/placeholder.svg?height=80&width=80",
    },
  },
  {
    id: "post-2",
    title: "Mastering Tailwind CSS",
    slug: "mastering-tailwind-css",
    excerpt:
      "Discover how to build beautiful user interfaces with Tailwind CSS, the utility-first CSS framework.",
    content: `
# Mastering Tailwind CSS

Tailwind CSS is a utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design, directly in your markup.

Instead of opinionated predesigned components, Tailwind provides low-level utility classes that let you build completely custom designs without ever leaving your HTML.

## Why Tailwind CSS?

Here's why you should consider Tailwind CSS for your next web project:

- No more custom CSS
- Responsive to the core
- Component-friendly
- Customizable design system
- Dark mode built in
- Excellent documentation

## Code Example

\`\`\`html
<div class="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
  <div class="flex-shrink-0">
    <img class="h-12 w-12" src="/img/logo.svg" alt="ChitChat Logo">
  </div>
  <div>
    <div class="text-xl font-medium text-black">ChitChat</div>
    <p class="text-gray-500">You have a new message!</p>
  </div>
</div>
\`\`\`
    `,
    coverImage: "/placeholder.svg?height=630&width=1200",
    publishedAt: "2023-06-22T14:30:00Z",
    authorId: "author-2",
    author: {
      id: "author-1",
      name: "John Doe",
      email: "john@example.com",
      avatar: "/placeholder.svg?height=80&width=80",
    },
  },
  {
    id: "post-3",
    title: "Building a Blog with Next.js",
    slug: "building-a-blog-with-nextjs",
    excerpt:
      "Step-by-step guide to creating a blog using Next.js, Tailwind CSS, and a headless CMS.",
    content: `
# Building a Blog with Next.js

Creating a blog with Next.js is a great way to learn the framework while building something useful. In this guide, we'll walk through the process of setting up a blog with Next.js, styling it with Tailwind CSS, and connecting it to a headless CMS.

## Setting Up the Project

First, let's create a new Next.js project:

\`\`\`bash
npx create-next-app my-blog
\`\`\`

Next, let's add Tailwind CSS to our project:

\`\`\`bash
npm install -D tailwindcss postcss autoprefixer
\`\`\`

Initialize Tailwind CSS:

\`\`\`bash
npx tailwindcss init -p
\`\`\`

## Creating Blog Posts

Now, let's create a simple blog post component that we can use to display our blog posts.

\`\`\`tsx
// components/PostCard.tsx
import Link from 'next/link'
import Image from 'next/image'

interface PostCardProps {
  title: string
  excerpt: string
  slug: string
  coverImage: string
}

export default function PostCard({ title, excerpt, slug, coverImage }: PostCardProps) {
  return (
    <div className="bg-white rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
      <Link href={\`/posts/\${slug}\`}>
        <div className="relative h-48">
          <Image
            src={coverImage || "/placeholder.svg"}
            alt={title}
            fill
            className="object-cover"
          />
        </div>
      </Link>
      <div className="p-6">
        <Link href={\`/posts/\${slug}\`}>
          <h3 className="text-xl font-bold mb-2 hover:text-gray-700">{title}</h3>
        </Link>
        <p className="text-gray-600">{excerpt}</p>
      </div>
    </div>
  )
}
\`\`\`
    `,
    coverImage: "/placeholder.svg?height=630&width=1200",
    publishedAt: "2023-07-10T09:15:00Z",
    authorId: "author-1",
    author: {
      id: "author-2",
      name: "Jane Smith",
      email: "jane@example.com",
      avatar: "/placeholder.svg?height=80&width=80",
    },
  },
];
export default async function Home() {
  return (
    <div className="min-h-screen bg-white">
      <section className="relative py-20 md:py-32 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-slate-50 to-slate-100 z-0" />
        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-6">
              Thoughts, stories and ideas.
            </h1>
            <p className="text-lg md:text-xl text-slate-600 mb-8">
              Welcome to our blog where we share insights, experiences, and
              knowledge on various topics.
            </p>
            <Link
              href="/blog"
              className="inline-flex items-center gap-2 bg-black text-white px-6 py-3 rounded-md font-medium hover:bg-slate-800 transition-colors"
            >
              Browse all articles
              <ArrowRight size={18} />
            </Link>
          </div>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold mb-12 text-center">
            Featured Posts
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {posts.slice(0, 6).map((post) => (
              <BlogCard key={post.id} post={post} />
            ))}
          </div>
          <div className="text-center mt-12">
            <Link
              href="/blog"
              className="text-black font-medium inline-flex items-center hover:underline"
            >
              View all posts
              <ArrowRight size={16} className="ml-2" />
            </Link>
          </div>
        </div>
      </section>

      <section className="py-16 bg-slate-50">
        <div className="container mx-auto px-4">
          <div className="max-w-2xl mx-auto text-center">
            <h2 className="text-3xl font-bold mb-4">
              Subscribe to our newsletter
            </h2>
            <p className="text-slate-600 mb-6">
              Get the latest posts delivered right to your inbox.
            </p>
            <form className="flex flex-col sm:flex-row gap-2 max-w-md mx-auto">
              <input
                type="email"
                placeholder="Enter your email"
                className="flex-1 px-4 py-3 rounded-md border border-slate-300 focus:outline-none focus:ring-2 focus:ring-black"
                required
              />
              <button
                type="submit"
                className="bg-black text-white px-6 py-3 rounded-md font-medium hover:bg-slate-800 transition-colors"
              >
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </section>
    </div>
  );
}
